export const GET_PRODUCTS_REQUEST = "GET/PRODUCTS/REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET/PRODUCTS/SUCCESS";
export const GET_PRODUCTS_ERROR = "GET/PRODUCTS/ERROR";

export const GET_TOTAL_PRODUCTS_REQUEST = "GET/TOTAL/PRODUCTS/REQUEST";
export const GET_TOTAL_PRODUCTS_SUCCESS = "GET/TOTAL/PRODUCTS/SUCCESS";
export const GET_TOTAL_PRODUCTS_ERROR = "GET/TOTAL/PRODUCTS/ERROR";
